Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8

src/server/shared/Database/QueryResult.h

Add support to MySQL 8.0
def my_bool
my_bool has been renamed to bool in MySQL 8.0.
https://dev.mysql.com/doc/refman/8.0/en/c-api-prepared-statement-data-structures.html

add MYSQL 8.0 macro

---

src/server/scripts/Toys/npc_toy.cpp

Port from JadeCore547 Source.

---

src/server/game/World/World.cpp

There probably needs to be a large refactoring effort to use consistent game time throughout the server, but this is a very small patch that fixes non-instant logout.

fix logout by regularly updating gametime

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp
src/server/scripts/Outland/zone_netherstorm.cpp

This skips the gossip menu/greeting for NPCs that have one quest available. The updated methods now match TC master branch.
Before this change:
1. Create a new Blood Elf
2. Talk to first quest giver
3. Note that you have to click past the greeting into the menu to auto accept the first quest (this is also the case for quest turn ins)
After this change:
1. Create a new Blood Elf
2. Talk to first quest giver
3. Greeting is skipped and first quest is auto-accepted

FIX: skip greeting for npcs with one quest

---

src/server/game/AI/CoreAI/GameObjectAI.h
src/server/game/AI/CreatureAI.h
src/server/game/AI/SmartScripts/SmartAI.cpp
src/server/game/AI/SmartScripts/SmartAI.h
src/server/game/Entities/Creature/GossipDef.cpp
src/server/game/Entities/Creature/GossipDef.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/Unit.h
src/server/game/Handlers/QuestHandler.cpp
src/server/game/LuaEngine/HookMgr.cpp
src/server/game/LuaEngine/HookMgr.h
src/server/game/Quests/QuestDef.h
src/server/game/Scripting/ScriptMgr.cpp
src/server/game/Scripting/ScriptMgr.h
src/server/game/Server/WorldSession.h

This reworks `Player::GetQuestDialogStatus` - functionality is based on TC master, and is mostly the same, except legendary icons are now supported with the expanded `QuestGiverStatus` enum. I manually verified each of the enum values, which is why it's slightly different than TC master.
There are basically two tests:
- General questing
- Icons should be correct when accepting, in progress, ready to turn in, etc.
- Legendary quest icon
- `.character level 90`
- `.go creature 514060`
- Verify correct color of quest icon (legendary is more orange than normal)

[Core/Questing] Rework GetQuestDialogStatus; support legendary quest icons

---

src/server/game/Spells/SpellEffects.cpp

The default position was always (0, 0, 0). This fixes spells like blink to teleport to the proper destination.

[Core/Spells] Fix spell effect leap (mage blink)

---

src/server/game/Globals/ObjectMgr.cpp
src/server/game/Globals/ObjectMgr.h
src/server/game/Handlers/QueryHandler.cpp

This fixes quest completion icons in the minimap; reverse quest relations were never populated so the `SMSG_QUEST_NPC_QUERY_RESPONSE` message was always empty.
Original bug:
1. Create new blood elf
2. Zoom minimap all the way in (`+`)
3. Accept first quest
4. `.quest complete 8325`
5. See 2x quest completion icons in the minimap:
Fixed with this PR:
1. Create new blood elf
2. Zoom minimap all the way in (`+`)
3. Accept first quest
4. `.quest complete 8325`
5. See 1x quest completion icon in the minimap:

[Core/Questing] Fix reverse quest relations and SMSG_QUEST_NPC_QUERY_RESPONSE

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/shared/DataStores/DBCEnums.h

This fixes resting in faction areas that do not use the area trigger system.
Test Alliance rest areas:
- `.tele valgarde` and walk into closest building, verify rested
- Make a new DK and verify rested in Acherus: The Ebon Hold
Test Horde rest areas:
- `.tele falconwingsq` and walk into building with curtains, verify rested
- Make a new DK and verify rested in Acherus: The Ebon Hold

[Core/Resting] set rest flag in faction area

---

sql/updates/master/world/2024_06_25_00_world.sql

- Fix location of Well Watcher Solanian https://www.wowhead.com/npc=15295/well-watcher-solanian
- Fix creatures to have random movement:
- Wretched Thug https://www.wowhead.com/npc=15645/wretched-thug
- Wretched Hooligan https://www.wowhead.com/npc=16162/wretched-hooligan
- Crazed Dragonhawk https://www.wowhead.com/npc=15650/crazed-dragonhawk
- Springpaw Stalker https://www.wowhead.com/npc=15651/springpaw-stalker
- Fix random movement of Crazed Dragonhawk https://www.wowhead.com/npc=15650/crazed-dragonhawk
- Previous inhabit type (air) caused constant movement, and was incorrect because this creature doesn't fly
- Fix MANY creatures by removing  `UNIT_FLAG_PVP_ATTACKABLE`
- This flag would cause creature names to show as red after they had been killed

[DB/World] Eversong Woods creature fixes

---

sql/updates/master/world/2024_06_27_00_world.sql
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Globals/ObjectMgr.h
src/server/game/Handlers/CharacterHandler.cpp

The custom spell casts from code were moved into a new table `playercreateinfo_cast_spell`. All of the existing spell casts were added to this table. Also:
- Fix Death Knight to activate Frost Presence on player create https://www.wowhead.com/cata/spell=48266/frost-presence
- Fix Warrior to activate Battle Stance on player create https://www.wowhead.com/cata/spell=2457/battle-stance
- Fix Gnome Irradiated Aura to use `playercreateinfo_cast_spell` instead of `spell_area` https://www.wowhead.com/cata/spell=80653/irradiated

[Core/Player] Add DB table playercreateinfo_cast_spell

---

src/server/game/Spells/Spell.cpp

From patch notes:
> Patch 3.1.0 (2009-04-14): You can no longer fail when Mining, Herbing, and Skinning.

[Core/Gathering] Never fail mining, herbing, skinning attempts

---

sql/updates/master/world/2024_06_27_01_world.sql
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Handlers/MiscHandler.cpp
src/server/game/Server/WorldSession.cpp
src/server/game/Spells/Auras/SpellAuras.cpp

This configures Pandaren action bars for all classes.
It also casts `Stance of the Fierce Tiger` https://www.wowhead.com/spell=103985/stance-of-the-fierce-tiger on Pandaren Monk player create, and fixes the core so this stance is not removed on logout.

Fix pandaren action bars

---

src/common/Threading/LockedQueue.h
src/server/game/Server/WorldSession.cpp

This allows addons like TradeSkillMaster and ElvUI to work with this core. Without this change, the loading bar stops at 90% and the server loops on the same 100 messages forever, never logging in the client.

[Core/PacketIO] Fix login with certain addons

---

.github/workflows/windows-build-release.yml

I copied and edited the `windows-build` workflow; now there are two:
`windows-build`:
- only runs on PR
- only builds; does not publish
`windows-build-release`:
- does not run on PR
- only runs on push
- builds and publishes
This should allow PRs to pass their status checks.

Fix failing windows PR checks

---

sql/updates/master/world/2024_06_29_01_world.sql
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Creature/GossipDef.cpp
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Globals/ObjectMgr.h

This updates `points_of_interest` and `creature_equip_template` db tables to use the same column names as TCPP, which makes them compatible with WPP.
To test `points_of_interest`:
- `.go c 98376`
- click on some POI menu items
- check that POI is displayed on map
To test `creature_equip_template`:
- `.go c 372315`
- check that `Huntsman Leopold` is using a polearm with a glow effect https://www.wowhead.com/item=32371/monster-polearm-epic-d-glow
It is important that the script is only executed once. If there's a better way to organize the SQL for this refactor, please let me know.

[DB/World] Update points_of_interest, creature_equip_template to match tc naming

---

src/server/game/Entities/Unit/Unit.cpp

This *partially* fixes #280 
This allows character movement to cancel feign death after it is successfully cast.

[Core/Spells] Properly remove spell auras on position update (like feign death)

---

src/server/game/Handlers/QueryHandler.cpp
src/server/game/Server/Packets/AllPackets.h
src/server/game/Server/Packets/QueryPackets.cpp
src/server/game/Server/Packets/QueryPackets.h
src/server/game/Server/WorldSession.h

This moves packet reading and writing for `CMSG_GAMEOBJECT_QUERY` and `SMSG_GAMEOBJECT_QUERY_RESPONSE` out of `QueryHandler` and into `QueryPackets`. No behavior change with this PR.
To test, empty client cache and view some game objects in the world. Locale should still be correct, etc.

[Core/PacketIO] Add game object query packets

---

src/server/game/Server/WorldSocket.cpp

Ping (sequence) and latency are read in the wrong order. This has a couple consequences:
1. The `SMSG_PONG` reply responds with the latency instead of the sequence, which causes `Received pong with old sequence` errors in the client console.
2. The latency set in `_worldSession->SetLatency(latency)` is incorrect
Changing the decode order fixes both of these issues, and client latency is now visible in game. Note that we still only use one connection, so latency will only display for `Home`.
This fixes #292

[Core/PacketIO] Properly decode CMSG_PING

---

src/server/database/Updater/DBUpdater.cpp

`--ssl=0` is only valid for mariadb client, so it has been removed. Also updated the full db release url that is logged.

[DB/World] Fix world db updates using mysql client

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/SpellEffects.cpp

This improves (but doesn't completely fix) auto shot for hunters.
1. Make a new hunter
2. `.char level 35`
3. Start to auto shot a creature
4. Cast feign death
5. Note the death animation is played and auto shot stops on the server
Bug that still exists after this PR:
- When the player is moved (to cancel feign death), the client still thinks the hunter is about to auto shot until ESC is pressed

[Core/Spells] Hunter auto shot improvements

---

src/server/game/Groups/Group.cpp
src/server/game/Groups/Group.h
src/server/game/Handlers/GroupHandler.cpp

- Each index in the `m_targetIcons` array is equal to `iconId`, so `targetGuid` should be saved to its own array index (0-7). At this moment, `targetGuid` is always written to index zero, and the server only stores the last `targetGuid` marked with an icon in its memory, but must store all 8 `targetGuid`s.
before fix ( index 0 rewrite ):
after fix ( `m_targetIcons` fully populated ):

[Core/Group] Target icons server side store fix

---

src/server/game/Groups/Group.cpp
src/server/game/Handlers/GroupHandler.cpp

[Core/Group] SendTargetIconList fix
- `TargetIcon`s should be send to new party/raid members ( as `RaidMarker`s do now )
- `TargetIcon`s should be send to logged in party/raid members ( as `RaidMarker`s do now )
to test PR:
- create party/raid ( 2 players minimum )
- mark targets with `TargetIcon`s
- invite 3rd player to party/raid
- this player will receive `TargetIcon`s
https://youtu.be/_3orpm96yH4

[Core/Group] SendTargetIconList fix

---

src/server/game/Chat/Chat.cpp

- no more spam of addons messages
- addons messages now properly send in LANG_ADDON language and invisible for players
how to test PR:
- install any addon that use addon language to talk with other players addons ( e. g. Details, Carbonite )
before fix:
after fix:

[Core/Chat] addons messages visibility fix

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Handlers/MovementHandler.cpp
src/server/game/Server/WorldSession.cpp
src/server/game/Server/WorldSession.h
src/server/game/Server/WorldSocket.cpp

The server was (like SkyFire) ignoring the movement info and generating a new timestamp on each write. This fixes that behavior, as well as including a movement fix that this core was missing.

[Core/Packet] Fix multiplayer movement

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Server/Protocol/Opcodes.h

* no more level-up sound on teleport (x64 client)
* no more "created" message in chat on teleport (x64 client)
* SMSG_READ_ITEM_RESULT_FAILED has wrong opcode
closes https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/issues/280

Level-up sound on teleport fix

---

src/server/game/AuctionHouse/AuctionHouseMgr.cpp
src/server/game/AuctionHouse/AuctionHouseMgr.h
src/server/game/AuctionHouseBot/AuctionHouseBot.cpp
src/server/game/AuctionHouseBot/AuctionHouseBot.h
src/server/game/AuctionHouseBot/AuctionHouseBotSeller.cpp
src/server/game/Handlers/AuctionHouseHandler.cpp

Use full `ObjectGuid` instead of `ObjectGuid::LowType` for owner and bidders in AH manager, AH bot and auction info in packets.

[Core/AuctionHouse] properly display names of auction owners and bidders

---

sql/updates/world/2024_10_16_01_world.sql

New invisibility setup is from TCPP; core previously used its own setup which was only configured for Alliance.
Now, portal will be visible during quests https://www.wowhead.com/quest=27203/the-maelstrom and https://www.wowhead.com/quest=27123/deepholm-realm-of-earth for Alliance and Horde

[DB/Quest] 27203 Fix Maelstrom portal visibility

---

src/server/database/Updater/DBUpdater.cpp
src/server/game/Entities/Creature/Creature.cpp

This was broken with https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/330 when `Creature.TriggerJustRespawned` was replaced with `m_triggerJustAppeared` and the initial value was changed from `false` to `true`.
This also fixes the db updater so it can create and populate auth and creature databases that don't already exist.

[Core/Creature] Fix quest 27123 wyvern ride

---

src/common/Collision/Management/MMapManager.cpp
src/server/game/Maps/Map.cpp

Updated to match TC log levels; see https://github.com/TrinityCore/TrinityCore/commit/42ab6010f862e530517e2acd347ef6230bcf1c3b
> Move "Could not load MMAP" log from ERROR to WARN as 99% of times is a false positive
This resolves https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/issues/222

[Core/Map] Lower some mmap logs from ERROR to WARN/DEBUG

---

src/server/game/AI/CoreAI/GameObjectAI.h
src/server/game/AI/SmartScripts/SmartAI.cpp
src/server/game/AI/SmartScripts/SmartAI.h
src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/GameObject/GameObject.h
src/server/game/Handlers/SpellHandler.cpp
src/server/game/Spells/SpellEffects.cpp
src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
src/server/scripts/Pandaria/MogushanVault/boss_feng.cpp
src/server/scripts/Pandaria/ThroneOfThunder/boss_horridon.cpp
src/server/scripts/World/go_scripts.cpp

This fixes tooltips and interaction with the Acherus Soul Prison game objects used in the quest https://www.wowhead.com/quest=12848/the-endless-hunger.
First, the `npc_unworthy_initiate` script called `prison->ResetDoorOrButton()` which left the game objects in a bad state (`GO_STATE_ACTIVE` instead of `GO_STATE_READY`). Now, `ResetDoorOrButton` will restore game object state from database. Fix is from https://github.com/TrinityCore/TrinityCore/commit/8a3f053a2f82460cf5d856404f6fcaf4b7eb44aa.
Second, `CMSG_GAMEOBJ_REPORT_USE` (attempting to use a locked game object) calls `OnGossipHello` "for backward compatibility" with nothing to disambiguate from `CMSG_GAMEOBJ_USE` (using a game object after successfully unlocking it). Now, an additional `isUse` parameter is passed. Fix is from …

Core/GameObject: fix acherus soul prison interaction

---

src/server/game/Pools/PoolMgr.cpp

With this fix, pooled creatures and gameobjects are properly added to the map.
I tested with cobalt https://www.wowhead.com/object=189978/cobalt-deposit - you can log guids in `PoolGroup<GameObject>::Spawn1Object(ActivePoolData& spawns, PoolObject* obj)` when `data->id == 189978` or something similar, then use `.go obj [guid]` to teleport directly to the cobalt node and verify that it's actually in the map.

Core/Pools: fix spawning pooled creatures and gameobjects

---

.github/workflows/windows-build-release.yml

From the last build workflow openssl has return this folder location:
-- Found OpenSSL: optimized;C:/Program Files/OpenSSL/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL/lib/VC/libcrypto64MDd.lib (found suitable version "3.1.1", minimum required is "1.1") found components: Crypto SSL
-- Found OpenSSL library: optimized;C:/Program Files/OpenSSL/lib/VC/libssl64MD.lib;debug;C:/Program Files/OpenSSL/lib/VC/libssl64MDd.lib;optimized;C:/Program Files/OpenSSL/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL/lib/VC/libcrypto64MDd.lib
-- Found OpenSSL headers: C:/Program Files/OpenSSL/include
I was specifing OpensSSL-Win64/ instead of OpenSsl/

Fix wrong path for openssl build workflow
