- sql/updates/characters/2022_03_25_00_characters_solocraft.sql
- src/server/scripts/Custom/solocraft.cpp
- src/server/worldserver/worldserver.conf.dist
Thanks to LannyE & acidmanifesto
> Solocraft system update

- src/server/game/Cfbg/Cfbg.cpp
> Core/Script CFBG

- src/server/scripts/Pandaria/ScarletHalls/boss_armsmaster_harlan.cpp
- src/server/scripts/Pandaria/ScarletHalls/boss_flameweaver_koegler.cpp
- src/server/scripts/Pandaria/ScarletHalls/boss_houndmaster_braun.cpp
- src/server/scripts/Pandaria/ScarletHalls/instance_scarlet_halls.cpp
> Core/Instances Scralett Halls

- src/server/scripts/Custom/StartingGuild.cpp
- src/server/worldserver/worldserver.conf.dist
> Core/Scripts Starting Guild

- src/server/game/AuctionHouse/AuctionHouseBot/AuctionHouseBot.cpp
- src/server/game/AuctionHouse/AuctionHouseBot/AuctionHouseBot.h
> Core/Scripts AHBot

- src/server/game/Miscellaneous/SharedDefines.h
Adding Enum BattlePayDistribution
> Adding Enum BattlePayDistribution

- src/server/game/CMakeLists.txt
- src/server/game/Grids/NGrid.h
- src/server/game/Server/WorldPacket.h
- src/server/game/World/World.cpp
- src/server/scripts/CMakeLists.txt
- src/server/scripts/ScriptLoader/ScriptLoader.cpp
- src/server/shared/Logging/Log.h
Rework Linux Clang Build without build eluna.Building eluna under Linux still has errors.
> Rework Linux Clang Build without build eluna

- dep/g3dlite/CMakeLists.txt
- dep/g3dlite/G3D-v9.0 hotfix1.diff
- dep/g3dlite/G3D-v9.0 hotfix13.diff
- dep/g3dlite/G3D-v9.0 hotfix14.diff
- dep/g3dlite/G3D-v9.0 hotfix16.diff
- dep/g3dlite/G3D-v9.0 hotfix2.diff
- dep/g3dlite/G3D-v9.0 hotfix3.diff
- dep/g3dlite/G3D-v9.0 hotfix4.diff
- dep/g3dlite/G3D-v9.0 hotfix5.diff
- dep/g3dlite/G3D-v9.0 hotfix6.diff
- dep/g3dlite/G3D-v9.0 hotfix7.diff
- dep/g3dlite/G3D-v9.0 hotfix8.diff
- dep/g3dlite/G3D-v9.0 hotfix9.diff
- dep/g3dlite/Readme.txt
- dep/g3dlite/include/G3D/Array.h
- dep/g3dlite/include/G3D/AtomicInt32.h
- dep/g3dlite/include/G3D/Matrix3.h
- dep/g3dlite/include/G3D/Ray.h
- dep/g3dlite/include/G3D/System.h
- dep/g3dlite/include/G3D/Vector3.h
- dep/g3dlite/include/G3D/g3dmath.h
- dep/g3dlite/include/G3D/platform.h
- dep/g3dlite/source/FileSystem.cpp
- dep/g3dlite/source/System.cpp
- dep/g3dlite/source/debugAssert.cpp
- dep/g3dlite/source/fileutils.cpp
Update g3dlite version to G3D-v9.0 hotfix16 to improve performance.
> Update g3dlite version to G3D-v9.0 hotfix16

- src/server/game/World/World.cpp
- src/server/game/World/World.h
- src/server/worldserver/worldserver.conf.dist
CORE*/Add config Server.Auto.Restart
> CORE*/Add config Server.Auto.Restart

- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Creature/Creature.h
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
- src/server/game/Handlers/NPCHandler.h
- src/server/game/World/World.cpp
- src/server/scripts/Commands/cs_reload.cpp
- src/server/shared/Database/Implementation/WorldDatabase.cpp
> [Core/System]Merge NpcText System from TC

- src/server/game/BattlePay/BattlePayMgr.cpp
- src/server/game/DataStores/DB2Utility.cpp
> Compile error fix

- src/LuaEngine/ItemMethods.h
Compile error fix of Lua by last commit
> Compile error fix of Lua by last commit

- src/LuaEngine/GameObjectMethods.h
- src/LuaEngine/GlobalMethods.h
- src/LuaEngine/LuaEngine.cpp
- src/LuaEngine/UnitMethods.h
Fix Lua Engine Compile error on Linux
> Fix Lua Engine Compile error on Linux

- src/server/game/AI/CreatureAI.cpp
- src/server/game/AI/CreatureAI.h
- src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
- src/server/game/AI/ScriptedAI/ScriptedCreature.h
- src/server/game/AI/ScriptedAI/ScriptedGossip.cpp
- src/server/game/AI/ScriptedAI/ScriptedGossip.h
- src/server/game/AI/SmartScripts/SmartAI.cpp
- src/server/game/AI/SmartScripts/SmartAI.h
- src/server/game/Entities/Creature/GossipDef.cpp
- src/server/game/Entities/Creature/GossipDef.h
- src/server/game/Scripting/ScriptMgr.h
- src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/instance_old_hillsbrad.cpp
- src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp
- src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.h
- src/server/scripts/World/npc_innkeeper.cpp
- src/server/scripts/World/npc_taxi.cpp
- src/server/shared/Utilities/Optional.h
Rework AddGossipItemFor.ScriptAI still has many function missing.
> Rework AddGossipItemFor

- src/server/game/Entities/Creature/GossipDef.cpp
> Fix Windows Compile

- src/server/scripts/Custom/CMakeLists.txt
- src/server/scripts/Custom/emo_stone.cpp
- src/server/scripts/Custom/emo_teleporter.cpp
> Z terragor patch emo (#61)

- src/server/game/Globals/ObjectMgr.cpp
- src/server/scripts/Commands/cs_reload.cpp
reduce difference of gameobject_locale system from TC
> [Core/System]reduce difference of gameobject_locale system from TC

- src/server/game/AI/SmartScripts/SmartAI.cpp
- src/server/game/AI/SmartScripts/SmartAI.h
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
> [Core/System]Reduce SmartAI diff

- CMakeLists.txt
- src/server/authserver/CMakeLists.txt
- src/server/collision/CMakeLists.txt
- src/server/game/Battlegrounds/RatedPvp.cpp
- src/server/game/CMakeLists.txt
- src/server/game/CustomLogs/CustomLogs.cpp
- src/server/game/Groups/Group.cpp
- src/server/scripts/CMakeLists.txt
- src/server/scripts/Kalimdor/zone_tanaris.cpp
- src/server/scripts/Pandaria/zone_isle_of_thunder.cpp
- src/server/scripts/Spells/spell_warrior.cpp
- src/server/shared/CMakeLists.txt
- src/server/worldserver/CMakeLists.txt
1.Update PCH model to new model
2.Update C++ Standard to C++ 17
3.Update CMake min version to 3.16.
4.Update new world database
> Update PCH model,C++ Standard

- .github/workflows/windows-build.yml
> Fully revent to old version

- src/server/game/AI/CoreAI/UnitAI.h
- src/server/game/World/World.cpp
Move some functions to C++ 17 standard
> Move some functions to C++ 17 standard

- src/server/game/Instances/InstanceSaveMgr.cpp
- src/server/scripts/Kalimdor/CavernsOfTime/DragonSoul/boss_madness_of_deathwing.cpp
- src/server/scripts/Northrend/Nexus/Oculus/boss_urom.cpp
- src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp
- src/server/scripts/Pandaria/MogushanPalace/instance_mogu_shan_palace.cpp
- src/server/scripts/Pandaria/ShadopanMonastery/boss_master_snowdrift.cpp
- src/server/scripts/Pandaria/SiegeOfOrgrimmar/boss_general_nazgrim.cpp
- src/server/scripts/Pandaria/SiegeOfOrgrimmar/boss_norushen.cpp
- src/server/scripts/Pandaria/SiegeOfOrgrimmar/boss_spoils_of_pandaria.cpp
- src/server/scripts/Pandaria/TerraceOfEndlessSpring/terrace_of_endless_spring.cpp
- src/server/scripts/Pandaria/ThroneOfThunder/boss_council_of_elders.cpp
- src/server/scripts/Pandaria/TimelessIsle/zone_timeless_isle.cpp
Update Scripts to C++ 17 Standard
> Update Scripts to C++ 17 Standard

- src/server/game/Server/WorldSocket.cpp
- src/server/scripts/Pandaria/HeartOfFear/boss_garalon.cpp
- src/server/scripts/Pandaria/ShadopanMonastery/boss_master_snowdrift.cpp
- src/server/shared/PrecompiledHeaders/sharedPCH.h
Fix compile warnring using GCC
> Fix compile warnring using GCC

- src/LuaEngine/CMakeLists.txt
- src/server/scripts/Commands/cs_support.cpp
- src/server/shared/CMakeLists.txt
- src/server/shared/PrecompiledHeaders/sharedPCH.h
> Fix lua build linux

- src/server/game/AI/CreatureAIImpl.h
- src/server/scripts/Pandaria/zone_kun_lai_summit.cpp
- src/server/scripts/World/world_map_scripts.cpp
Fix linux build after last merge
> Fix linux build after last merge

- src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
> fix compile error

- src/server/game/AI/CreatureAI.h
- src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
- src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.h
- src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.h
Fix start event of BattleForMountHyjal
> Fix start event of BattleForMountHyjal

- CMakeLists.txt
- README.md
- src/server/shared/Cryptography/OpenSSLCrypto.cpp
- src/server/shared/Cryptography/OpenSSLCrypto.h
> Add OpenSSL 3.0 support

- src/server/game/BattlePay/BattlePayMgr.cpp
- src/server/game/Globals/ObjectMgr.cpp
- src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
Replace hardcoded gossips.
Reduce compile warning.
> Replace BattleForMountHyjal hardcoded gossips

- src/server/game/Achievements/AchievementMgr.cpp
- src/server/game/Entities/Creature/GossipDef.cpp
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
- src/server/game/Quests/QuestDef.h
- src/server/game/World/World.cpp
- src/server/shared/Common.h
Change achievement,quest_objectives locale table struct from TC table struct.
Import data from TDB
> Change achievement locale table struct from TC table struct.

- src/server/game/Achievements/AchievementMgr.h
- src/server/game/AuctionHouse/AuctionHouseMgr.cpp
- src/server/game/AuctionHouse/AuctionHouseMgr.h
- src/server/game/Chat/ChatLink.cpp
- src/server/game/Entities/Corpse/Corpse.h
- src/server/game/Entities/Creature/Creature.h
- src/server/game/Entities/Creature/GossipDef.cpp
- src/server/game/Entities/GameObject/GameObject.h
- src/server/game/Entities/Item/Container/Bag.h
- src/server/game/Entities/Item/Item.cpp
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
- src/server/game/Instances/InstanceSaveMgr.cpp
- src/server/game/Instances/InstanceSaveMgr.h
- src/server/game/Quests/QuestDef.h
- src/server/game/World/World.cpp
- src/server/scripts/Commands/cs_lookup.cpp
- src/server/scripts/Commands/cs_reload.cpp
Change Quest template locale to TC struct.Import TC quest locale data.
> Change Quest template locale to TC struct

- sql/updates/master/characters/2023_01_20_characters_pool_quest_save.sql
DB/Characters: add missing table
> DB/Characters: add missing table

- sql/updates/master/archive/2023_01_20_archive_currency_transactions.sql
Fix crash 
Fix currency_transactions
> DB/Archive Fix crash

- sql/updates/master/world/022_07_22_00_Quest_Great_Vessel_of_Salvation_ID_31082.sql
*World of Warcraft Quest Guide Great Vessel of Salvation  ID 31082* https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/issues/138
> DB/FIX World of Warcraft Quest Guide Great Vessel of Salvation  ID 31082

- src/server/scripts/Toys/CMakeLists.txt
- src/server/scripts/Toys/npc_toy.cpp
> Port from JadeCore547 Source.

- sql/2023_11_16_world_03.sql
Database: Fixed phase after quest reward.
> Database: Fixed phase after quest reward.

- sql/updates/master/world/2023_11_21_world_00.sql
Database: Added OfferRewardText and RequestItemsText for some quests on wandering isle.
> Database: Added OfferRewardText and RequestItemsText

- sql/updates/master/world/2023_11_21_world_01.sql
Database: Added some OfferRewardText and RequestItemsText for quests in 'The Singing Pools'
> Database: Added some OfferRewardText and RequestItemsText

- sql/updates/master/world/world_2023_11_01_23_52.sql
- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Core/Script: Fix Quest "Death Comes From On High"
> Core/Script: Fix Quest "Death Comes From On High"

- sql/updates/master/world/2023_11_29_01_world_creature_template.sql
- sql/updates/master/world/2023_11_29_02_world_creature_text.sql
- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Fixed movement Eye of Acherus #6607
> Fixed movement Eye of Acherus #6607

- sql/base/characters.sql
> [SQL/Base] Fix Characters base sql import error

- sql/base/auth.sql
> [SQL/Base] Remove MariaDB unsupported COLLATE

- src/server/game/DungeonFinding/LFGMgr.cpp
- src/server/game/Handlers/CharacterHandler.cpp
- src/server/game/World/World.cpp
- src/server/game/World/World.h
> [Core/World] Remove whisper debug text

- dep/jemalloc/CMakeLists.txt
- src/tools/map_extractor/CMakeLists.txt
- src/tools/mmaps_generator/CMakeLists.txt
- src/tools/vmap4_assembler/CMakeLists.txt
- src/tools/vmap4_extractor/CMakeLists.txt
> core/mmap: fix debian build

- sql/base/characters.sql
- sql/updates/master/characters/2024_03_31_00_characters_solocraft.sql
- src/server/scripts/Custom/solocraft.cpp
> [Custom/Solocraft] Fix incorrect buff remove

- src/server/collision/BoundingIntervalHierarchyWrapper.h
- src/server/collision/DynamicTree.cpp
- src/server/collision/RegularGrid.h
- src/tools/mmaps_generator/IntermediateValues.h
- src/tools/mmaps_generator/MapBuilder.cpp
- src/tools/mmaps_generator/MapBuilder.h
- src/tools/mmaps_generator/PathGenerator.cpp
- src/tools/mmaps_generator/TerrainBuilder.cpp
- src/tools/mmaps_generator/TerrainBuilder.h
> [Tools/MMapsGenerator] Update MMapsGenerator Part 1

- src/server/game/Server/Protocol/PacketLog.cpp
This makes it easy to process server-generated packet logs with my WowPacketParser branch at https://github.com/jasongdove/WowPacketParser/tree/V5_4_8_18414
- Update `worldserver.conf` to have a valid `LogsDir` (folder) and `PacketLogFile` (relative file name - like `worldserver.pkt`).
- Start server
- Connect, enter world, exit game
- Run generated `PacketLogFile` through WowPacketParser to see communication details between client and server
> Add packet log header

- sql/updates/master/world/2024_06_22_00_world.sql
- sql/updates/master/world/2024_XX_XX_XX_world.sql
- src/server/game/Conditions/ConditionMgr.cpp
- src/server/game/Conditions/ConditionMgr.h
- src/server/game/Entities/Object/Object.cpp
- src/server/game/Entities/Object/Object.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
- src/server/game/Handlers/GroupHandler.cpp
- src/server/game/Instances/InstanceScript.cpp
- src/server/game/Maps/Map.cpp
- src/server/game/Maps/PhaseMgr.cpp
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/game/World/World.cpp
You can test its correct functioning by creating a panda, goblin or worgen and making their respective chains. You can check the terrainswamp added by using the gps command.
> [Core/TerrainSwamps] TerrainSwamps system modernized

- src/common/Collision/Models/GameObjectModel.cpp
This code didn't match the extractor: the `isWmo` field needs to be read from each record.
Before this change, on startup:
```
Loading GameObject models...
File 'GameObjectModels.dtree' seems to be corrupted!
>> Loaded 0 GameObject models in 1 ms
```
With the fix:
```
Loading GameObject models...
>> Loaded 4787 GameObject models in 3 ms
```
Note that these log messages only display with `-DTOOLS=0` :man_shrugging:
> fix loading game object models

- sql/updates/master/world/2024_07_18_00_world.sql
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Handlers/QuestHandler.cpp
- src/server/game/Quests/QuestDef.cpp
- src/server/game/Quests/QuestDef.h
This fixes a regression from https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/262
1. Create new blood elf
2. Accept first quest
3. Kill 1x mana wyrm
4. Verify quest objective shows 1/6 kills
5. Log out
6. Log in to same character
7. Verify quest objective still shows 1/6 kills
This also removes some unused quest special flags and the associated pserver quests from the db.
> [Core/Questing] Fix quest objective loading

- src/server/game/Handlers/BattlePayHandler.cpp
> [Core/BattlePay] Fix BattlePay boost opcode

- src/server/game/Entities/Player/Player.cpp
Fixes a crash introduced by #300
> [Core/Maps] Fix initial visible packets crash

- src/server/game/Entities/Object/Object.cpp
- src/server/game/Entities/Object/Object.h
- src/server/game/Spells/Spell.h
- src/server/game/Spells/SpellEffects.cpp
Use for testing the spell: https://www.wowhead.com/spell=135122/summon-ore-from-energized-iron-pt-3
> [Core/Spells] Fix SPELL_EFFECT_SUMMON_PERSONAL_GAMEOBJECT

- sql/updates/world/2024_09_24_00_world.sql
Fix Paladin Judgement power gain. Thanks Sjenkie from discord for report.
> [Spell/Paladin] Fix Paladin Judgement power gain

- src/server/game/Entities/Player/Player.cpp
- src/server/game/LuaEngine/GlobalMethods.h
- src/server/game/LuaEngine/LuaFunctions.cpp
- src/server/game/Maps/Map.cpp
- src/server/game/Maps/Map.h
- src/server/game/Server/Packets/MiscPackets.cpp
- src/server/game/Server/Packets/MiscPackets.h
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/game/Weather/Weather.cpp
- src/server/game/Weather/Weather.h
- src/server/game/Weather/WeatherMgr.cpp
- src/server/game/Weather/WeatherMgr.h
- src/server/game/World/World.cpp
- src/server/scripts/Commands/cs_misc.cpp
- src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp
- src/server/scripts/Kalimdor/ThroneoftheFourWinds/boss_alakir.cpp
- src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
- src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
1.Split SMSG_OVERRIDE_LIGHT to MiscPackets
2.Remove SMSG_WEATHER From scripts
> [Core/Packet] Split SMSG_OVERRIDE_LIGHT to MiscPackets

- src/server/game/Battlegrounds/Battleground.cpp
- src/server/game/Battlegrounds/BattlegroundMgr.cpp
- src/server/game/Battlegrounds/BattlegroundQueue.cpp
- src/server/game/Battlegrounds/RatedPvp.cpp
- src/server/game/BlackMarket/BlackMarketMgr.cpp
- src/server/game/DungeonFinding/LFGMgr.cpp
- src/server/game/DungeonFinding/LFGQueue.cpp
- src/server/game/Entities/AreaTrigger/AreaTrigger.cpp
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/SocialMgr.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Groups/Group.cpp
- src/server/game/Handlers/GroupHandler.cpp
- src/server/game/Handlers/MiscHandler.cpp
- src/server/game/Handlers/QuestHandler.cpp
- src/server/game/Spells/SpellEffects.cpp
- src/server/game/Warden/WardenWin.cpp
- src/server/scripts/Commands/cs_character.cpp
- src/server/scripts/Commands/cs_misc.cpp
> 根据原版源代码中的FindPlayerInOrOutOfWorld函数 将FindPlayer修改为FindConnectedPlayer

- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
- src/server/scripts/Commands/cs_gobject.cpp
To test game object creation:
- `.gobj add 209058` (balloon for example, entry doesn't matter)
- game object is immediately visible in game
- look at `gameobject` table sorted by `guid` desc and confirm new game object with largest `guid`
To test creature/npc creation:
- `.npc add 18166` (Archmage Khadgar)
- npc is immediately visible in game
- look at `creature` table sorted by `guid` desc and confirm new creature with largest `guid`
> [Core/GameObject] generate proper creature and game object ids

- .github/workflows/linux_gcc.yml
- .github/workflows/windows-build-release.yml
- .github/workflows/windows-build.yml
- CMakeLists.txt
- cmake/compiler/gcc/settings.cmake
- dep/boost/CMakeLists.txt
- src/common/Asio/AsioHacksFwd.h
- src/common/Asio/DeadlineTimer.h
- src/common/Asio/Resolver.h
- src/common/Asio/Strand.h
- src/common/Logging/Log.h
- src/common/Threading/ProducerConsumerQueue.h
- src/server/authserver/Main.cpp
- src/server/authserver/Server/AuthSocketMgr.h
- src/server/game/Server/WorldSocketMgr.cpp
- src/server/shared/Networking/AsyncAcceptor.h
- src/server/shared/Networking/NetworkThread.h
- src/server/shared/Networking/SocketMgr.h
- src/server/shared/Realms/RealmList.cpp
- src/server/shared/Realms/RealmList.h
- src/server/worldserver/Main.cpp
Refactored boost, i tried not to change too much of the base code to avoid massive commit and keep it simple.
> Refatoring boost to use modern system

- .github/workflows/windows-build-release.yml
- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Creature/Creature.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
Fix for https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/issues/383
But mob cannot swim on deep water, i'm pretty sure its related to how the swim packet movement are being sent
> Water evade
